# Generated by Django 4.1.4 on 2022-12-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='rate',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='product',
        ),
    ]
