# Generated by Django 4.1.4 on 2022-12-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_reviews_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='posts.products'),
        ),
    ]
