# Generated by Django 4.1.4 on 2022-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_hashtag_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_table',
            field=models.BooleanField(default=True),
        ),
    ]
