# Generated by Django 4.1.4 on 2022-12-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_product_review_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review_table',
            new_name='reviewtable',
        ),
    ]
